### PR TITLE
Nette\Forms\Container::getValues dynamic return type

### PR DESCRIPTION
**Pull request by CZechBoY**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Nice, thank you! I can merge it once you fix the build.

**Comment by CZechBoY** [comment]
Ok, I am stuck with how to fix this phpstan error. Should I just add phpdoc type to array and tell phpstan that it is Expr? Or create mock/real Expr?
Thanks.

**Comment by CZechBoY** [comment]
aarg, that PHPUnit mocking... Is there any extension for phpstan for that?

**Comment by CZechBoY** [comment]
@ondrejmirtes thanks.
What about that PHPUnit bridge?

**Comment by ondrejmirtes** [comment]
PHPStan is not yet quite ready for PHPUnit extension. Things missing:

* intersection types (so that methods from multiple classes can exist on an object and at the same time, it does not matter that MockedClass|PHPUnit_Mock_MockObject is passed somewhere PHPUnit_Mock_MockObject is not expected)
* deep inspection of called methods, so that PHPStan can figure out that even if the method has return type `MockedClass`, it's safe to call `expects`, `method` etc. on them because it creates a mock object inside.

So once we have these, it will be really easy to create an extension :) Maybe it won't even be needed.

**Pull request merged**
