### PR TITLE
Fix PresenterGetSessionReturnTypeExtension file name

### PR DESCRIPTION
**Pull request by pepakriz**

### CODE REVIEW

**Comment by CZechBoY** [comment]
I think nette/application should be in project dependency (as other nette/* dependencies)

**Comment by pepakriz** [comment]
I think other nette/* dependencies should be in dev section too or in suggestions

**Comment by pepakriz** [comment]
I can remove `nette/application` completely - class constants don't require class itself (https://3v4l.org/oNI7n). But there is some phpstan rule which checks this situation and prints error. Maybe ignore in `ignoreErrors` section, I don't know...

**Comment by ondrejmirtes** [comment]
I added `nette/application` as `require` dependency, because that't where all the other dependencies currently are. For 0.10, I plan to remove all these dependencies from all extensions, add unsupported one to `conflict` key and only the required for the build add to `require-dev`.

**Comment by ondrejmirtes** [comment]
Thanks!

**Pull request merged**
