### PR TITLE
Added more universal objects

### PR DESCRIPTION
**Pull request by CZechBoY**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
`Nette\Security\IIdentity` is not a universal object crate
ArrayHash does not need adding because that's already covered by the fact it extends `\stdClass`.

**Comment by CZechBoY** [comment]
ok, I realized that ArrayHash was random fail and I can't reproduce it again.
What about implementation of `IIdentity` -> `Nette\Security\Identity`?
Also I realized that `ITemplate` is not universal class.

**Comment by ondrejmirtes** [comment]
Can you squash the second commit into the first one? Also I'd leave ITemplate in, not because it's a universal object crate, but because it's typehinted as such in Control::getTemplate().

**Comment by CZechBoY** [comment]
Yes, that was the initial reason why I added that.
I will squash it together after I add back the ITemplate.

**Comment by CZechBoY** [comment]
@ondrejmirtes Check now :-)

**Comment by ondrejmirtes** [comment]
Thanks! 👍

**Pull request merged**
