### PR TITLE
Readme: fix code samples

### PR DESCRIPTION
**Pull request by f3l1x**
Get rid of the red background.

image

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
It's better to remove the yaml highlighter, as I do it in the main PHPStan readme: https://raw.githubusercontent.com/phpstan/phpstan/master/README.md

**Comment by f3l1x** [comment]
Done. WDYT?

**Comment by ondrejmirtes** [comment]
It would be better to leave the tab indentation in.

**Comment by f3l1x** [comment]
Understand. I am closing it so. ;-)

**Pull request closed without merging**
