### PR TITLE
Move redirect() from Presenter to Component

### PR DESCRIPTION
**Pull request by MartkCz**
https://github.com/nette/application/blob/master/src/Application/UI/Component.php#L292

https://github.com/nette/application/blob/master/src/Application/UI/Component.php#L308

### CODE REVIEW

**Comment by spaze** [comment]
I hit the issue earlier today (missing `redirectPermanent` either on `Component` or `Presenter`), so I've created a PR in nette/application https://github.com/nette/application/pull/304

**Comment by spaze** [comment]
The nette/application PR has been merged, pending release.

**Comment by ondrejmirtes** [comment]
Since https://github.com/nette/application/pull/304 is merged I think there's no more need for this :)

**Comment by spaze** [comment]
And the `return never` tag has now been released in nette/application 3.1.10.

**Pull request closed without merging**
